### ISSUE TITLE
User testing - Round 1

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/pwc#62]
## Overall
👍 

## To-do
- [x] Feedback when saving preferences
- [x] Use "check" icon for recording prayer
- [x] FAB easy to miss on desktop
- [x] Time stamp for last recorded prayer
